name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
excerpt_separator: <!--excerpt-->

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "default"