name: Tomas Liscak
markdown: kramdown
excerpt_separator: <!--excerpt-->

collections:
  web_publication:
    output: true

  artificial_intelligence:
    output: true

  cycling:
    output: true

defaults:
  -
    scope:
      path: "" 
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "post"
  -
    scope:
      path: "" 
      type: "cycling"
    values:
      layout: "cycling"
  -
    scope:
      path: "" 
      type: "web_publication"
    values:
      teacher: "Marian Simko"
      room: -1.42
      layout: "web_publications"
  -
    scope:
      path: "" 
      type: "artificial_intelligence"
    values:
      teacher: "Ivan Kapustik"
      room: 1.30b
      layout: "artificial_intelligence"

